---
- name: "Install loki for cloudkitty"
  hosts: localhost
  gather_facts: true
  environment:
    KUBECONFIG: "{{ ansible_env.HOME + '/.kube/config' }}"
    PATH: "{{ ansible_env.PATH }}"
  tasks:
    - name: Wait for the route kind to be present in the cluster
      ansible.builtin.command:
        cmd:
          oc api-resources --api-group=route.openshift.io --no-headers
      delay: 10
      retries: 30
      register: route_api_check
      until: route_api_check.stdout_lines | length != 0

    - name: Deploy loki operator
      ansible.builtin.command:
        cmd: |
          oc apply -f {{ playbook_dir }}/deploy-loki-for-ck.yaml

    - name: Wait up to 5 minutes until the Loki CSV is Succeeded
      ansible.builtin.command:
        cmd: >
          oc get csv -n openshift-operators-redhat -o json
      ignore_errors: true
      register: output
      until: >
        output.rc == 0 and
        (output.stdout | from_json)["items"]
        | selectattr('metadata.name', 'match', 'loki-operator.*')
        | selectattr('status', 'defined')
        | selectattr('status.phase', 'defined')
        | selectattr('status.phase', 'equalto', 'Succeeded')
        | list | length > 0
      retries: 30
      delay: 10
